# Generated by Django 4.2.1 on 2023-05-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_populate_wilayas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetransportmean',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='sitetransportmean',
            name='site',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agent_username',
        ),
        migrations.AddField(
            model_name='touristicsite',
            name='Transport_Mean',
            field=models.ManyToManyField(related_name='TransportMean', to='app.transportmean'),
        ),
        migrations.AddField(
            model_name='touristicsite',
            name='Working_Time',
            field=models.ManyToManyField(related_name='WorkingDayTime', to='app.workingdaytime'),
        ),
        migrations.DeleteModel(
            name='SiteTiming',
        ),
        migrations.DeleteModel(
            name='SiteTransportMean',
        ),
    ]
