# Generated by Django 4.2.1 on 2023-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_touristicsite_current_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristicsite',
            name='site_type',
            field=models.CharField(choices=[('Lieu Naturel', 'Lieu Naturel'), ('Monument Historique', 'Monument Historique'), ('Site Religieux', 'Site Religieux'), ('Centre de Loisir', 'Centre de Loisir'), ('Hébergement', 'Hébergement')], max_length=255),
        ),
    ]
