# Generated by Django 4.2.1 on 2023-06-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_touristicsite_site_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='created_at',
        ),
    ]
